---
- hosts: localhost
  connection: local
  roles:
    - role: elliotweiser.osx-command-line-tools
      tags: [bootstrap, command-line-tools]

    - role: homebrew
      tags: [bootstrap, homebrew]

    - role: martianplatypus.python_mac
      tags: [bootstrap, python3, python]
